version: "3"

services:
  ftp-server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp-server
    ports:
      - "${FTP_PORT}:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: "${FTP_USER}"
      FTP_USER_PASS: "${FTP_PASSWORD}"
      FTP_USER_HOME: "${FTP_HOME}"
    volumes:
      - ./ftpdata:${FTP_HOME}
